### ISSUE TITLE
decode_rle_channel: Can't convert String into Integer

### ISSUE THREAD

**Issue by teejteej** [layervault/psd_native#1]
Hello,

Using the latest psd.rb (1.4.2) and psd_native (0.5.0) I get the following error while running `parse!` on the psd object:

```
/bundler/gems/psd.rb-e3e2230215d9/lib/psd/image_formats/layer_rle.rb:20:in `decode_rle_channel': can't convert String into Integer (TypeError)
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd/image_formats/layer_rle.rb:20:in `parse_channel_data!'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd/image_formats/rle.rb:9:in `parse_rle!'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd/channel_image.rb:89:in `parse_image_data!'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd/channel_image.rb:63:in `block in parse'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd/channel_image.rb:44:in `each'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd/channel_image.rb:44:in `parse'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd/layer/channel_image.rb:8:in `parse_channel_image'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd/layer_mask.rb:59:in `block in parse'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd/layer_mask.rb:57:in `each'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd/layer_mask.rb:57:in `parse'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd.rb:115:in `layer_mask'
    from /bundler/gems/psd.rb-e3e2230215d9/lib/psd.rb:76:in `parse!'
```

**Comment by meltingice** [comment]
I can't seem to replicate this. Can you give any more information or some of the code you're using? Is it limited to the PSD you're attempting to parse or all PSDs?

**Comment by teejteej** [comment]
I reinstalled with ruby-2.0.0-p247 (previous version was  ruby-1.9.3-p194), and everything works fine now!

**Comment by meltingice** [comment]
Ah gotcha. That means this was a character encoding issue. Needs that silly `# encoding: UTF-8` in the file to work with 1.9.
